version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-olff87oxb3a1"
s3_prefix = "sam-app"
region = "ap-northeast-1"
profile = "t2k"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

