AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  divers-ocean-map
  
  Sample SAM Template for divers-ocean-map

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  ScrapingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/scraping/
      Handler: scraping
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMODB_ENDPOINT: dummy # ローカルで環境変数を設定するために必要
          DYNAMODB_TABLE_NAME: !Ref OceanDynamoDBTable
          ENV: dummy # ローカルで環境変数を設定するために必要
  OceanFetchAPI:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/api
      Handler: api
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        GetLatestOcean:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/oceans/{name}
            Method: GET
        GetAllLatestOceans:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/oceans/
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMODB_ENDPOINT: dummy # ローカルで環境変数を設定するために必要
          DYNAMODB_TABLE_NAME: !Ref OceanDynamoDBTable
          ENV: dummy # ローカルで環境変数を設定するために必要
  OceanDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "LocationName"
          AttributeType: "S"
        -
          AttributeName: "MeasuredTime"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "LocationName"
          KeyType: "HASH"
        - 
          AttributeName: "MeasuredTime"
          KeyType: "RANGE"        
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: "Oceans"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldAPI:
    # Description: "API Gateway endpoint URL for Prod environment for First Function"
    # Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ScrapingFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ScrapingFunction.Arn
  ScrapingFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ScrapingFunctionRole.Arn
