@startuml
namespace iop {
    class ScrapingServiceIzuOceanParkImpl << (S,Aquamarine) >> {
        - logging *logging.OceanLoggingImpl
        - name string
        - url string
        - queryTemperature string
        - queryVisibility string
        - queryMeasuredTime string

        - fetchDocument(url string) (*goquery.Document, error)
        - fetchTemperature(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchVisibility(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchMeasuredTime(query string, doc *goquery.Document, ocean *model.Ocean) error

        + Scrape() (*model.Ocean, error)

    }
}

"service.ScrapingService" <|-- "iop.ScrapingServiceIzuOceanParkImpl"

namespace logging {
    interface OceanLogging  {
        + Info(message ...string) 
        + Info(message ...string) 

    }
    class OceanLoggingImpl << (S,Aquamarine) >> {
        - requestID string
        - requestID string

        + Info(message ...string) 
        + Info(message ...string) 

    }
}

"logging.OceanLogging" <|-- "logging.OceanLoggingImpl"

namespace model {
    class Ocean << (S,Aquamarine) >> {
        + LocationName string
        + URL string
        + Temperature Temperature
        + Visibility Visibility
        + MeasuredTime time.Time
        + LocationName string
        + URL string
        + Temperature Temperature
        + Visibility Visibility
        + MeasuredTime time.Time

    }
    class Temperature << (S,Aquamarine) >> {
        + Min int
        + Med int
        + Max int
        + Min int
        + Med int
        + Max int

    }
    class Visibility << (S,Aquamarine) >> {
        + Min int
        + Med int
        + Max int
        + Min int
        + Med int
        + Max int

    }
}


namespace repository {
    interface OceanRepository  {
        + Store(ocean *model.Ocean) error

    }
    class OceanRepositoryImpl << (S,Aquamarine) >> {
        - logging *logging.OceanLoggingImpl
        - db *service.DynamoDBServiceImpl

        + Store(ocean *model.Ocean) error

    }
}

"repository.OceanRepository" <|-- "repository.OceanRepositoryImpl"

namespace service {
    interface DynamoDBService  {
        + CreateIfNotExist( *model.Ocean) error
        + CreateIfNotExist( *model.Ocean) error

    }
    class DynamoDBServiceImpl << (S,Aquamarine) >> {
        - tableName string
        - dynamoDB *dynamodb.DynamoDB
        - logging *logging.OceanLoggingImpl
        - tableName string
        - dynamoDB *dynamodb.DynamoDB

        + FetchLatestOcean(locationName string) (*model.Ocean, error)
        + FetchAllLatestOceans() ([]*model.Ocean, error)
        + CreateIfNotExist(ocean *model.Ocean) error

    }
    interface ScrapingService  {
        + Scrape() (*model.Ocean, error)

    }
}

"service.DynamoDBService" <|-- "service.DynamoDBServiceImpl"

namespace tiba {
    class ScrapingServiceUkishimaTibaImpl << (S,Aquamarine) >> {
        - logging *logging.OceanLoggingImpl
        - name string
        - url string
        - queryArticle string
        - queryMeasuredTime string

        - fetchDocument(url string, ocean *model.Ocean) (*goquery.Document, error)
        - fetchTemperature(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchVisibility(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchMeasuredTime(query string, doc *goquery.Document, ocean *model.Ocean) error

        + Scrape() (*model.Ocean, error)

    }
}

"service.ScrapingService" <|-- "tiba.ScrapingServiceUkishimaTibaImpl"

namespace ukishima {
    class ScrapingServiceUkishimaNishiizuImpl << (S,Aquamarine) >> {
        - logging *logging.OceanLoggingImpl
        - name string
        - url string
        - queryArticle string
        - queryDate string

        - fetchDocument(url string, ocean *model.Ocean) (*goquery.Document, error)
        - fetchTemperature(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchVisibility(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchMeasuredTime(query string, doc *goquery.Document, ocean *model.Ocean) error

        + Scrape() (*model.Ocean, error)

    }
}

"service.ScrapingService" <|-- "ukishima.ScrapingServiceUkishimaNishiizuImpl"

@enduml
