@startuml
namespace logging {
    interface OceanLogging  {
        + Info(message ...string) 

    }
    class OceanLoggingImpl << (S,Aquamarine) >> {
        - requestID string

        + Info(message ...string) 

    }
}

"logging.OceanLogging" <|-- "logging.OceanLoggingImpl"

namespace model {
    class Ocean << (S,Aquamarine) >> {
        + LocationName string
        + URL string
        + Temperature Temperature
        + Visibility Visibility
        + MeasuredTime time.Time

    }
    class Temperature << (S,Aquamarine) >> {
        + Min int
        + Med int
        + Max int

    }
    class Visibility << (S,Aquamarine) >> {
        + Min int
        + Med int
        + Max int

    }
}


namespace service {
    interface DynamoDBService  {
        + CreateIfNotExist( *model.Ocean) error

    }
    class DynamoDBServiceImpl << (S,Aquamarine) >> {
        - tableName string
        - dynamoDB *dynamodb.DynamoDB

        + CreateIfNotExist(ocean *model.Ocean) error

    }
    interface ScrapingService  {
        + Scrape() (*model.Ocean, error)

    }
    class ScrapingServiceImpl << (S,Aquamarine) >> {
        - url string
        - db *DynamoDBServiceImpl
        - logging *logging.OceanLoggingImpl

        + Store(ocean *model.Ocean) error

    }
    class ScrapingServiceIzuOceanParkImpl << (S,Aquamarine) >> {
        - queryTemperature string
        - queryVisibility string
        - queryMeasuredTime string

        + ScrapingService *ScrapingServiceImpl

        - fetchDocument(url string) (*goquery.Document, error)
        - fetchTemperature(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchVisibility(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchMeasuredTime(query string, doc *goquery.Document, ocean *model.Ocean) error

        + Scrape() (*model.Ocean, error)

    }
    class ScrapingServiceUkishimaNishiizuImpl << (S,Aquamarine) >> {
        - queryArticle string
        - queryDate string

        + ScrapingService *ScrapingServiceImpl

        - fetchDocument(url string, ocean *model.Ocean) (*goquery.Document, error)
        - fetchTemperature(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchVisibility(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchMeasuredTime(query string, doc *goquery.Document, ocean *model.Ocean) error

        + Scrape() (*model.Ocean, error)

    }
    class ScrapingServiceUkishimaTibaImpl << (S,Aquamarine) >> {
        - queryArticle string
        - queryMeasuredTime string

        + ScrapingService *ScrapingServiceImpl

        - fetchDocument(url string, ocean *model.Ocean) (*goquery.Document, error)
        - fetchTemperature(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchVisibility(query string, doc *goquery.Document, ocean *model.Ocean) error
        - fetchMeasuredTime(query string, doc *goquery.Document, ocean *model.Ocean) error

        + Scrape() (*model.Ocean, error)

    }
}

"service.DynamoDBService" <|-- "service.DynamoDBServiceImpl"
"service.ScrapingService" <|-- "service.ScrapingServiceIzuOceanParkImpl"
"service.ScrapingService" <|-- "service.ScrapingServiceUkishimaNishiizuImpl"
"service.ScrapingService" <|-- "service.ScrapingServiceUkishimaTibaImpl"

@enduml
