@startuml
namespace service {
    interface DynamoDBService  {
        + NewDynamoDBService() *DynamoDBServiceImpl
        + Create( *model.Ocean) error

    }
    class DynamoDBServiceImpl << (S,Aquamarine) >> {
        - endpoint string
        - tableName string
        - dynamoDB *dynamodb.DynamoDB

        + Create(ocean *model.Ocean) error

    }
    interface ScrapingService  {
        + Scrape(url string) (*model.Ocean, error)

    }
    class ScrapingServiceImpl << (S,Aquamarine) >> {
        + Scrape(url string) (*model.Ocean, error)

    }
}

"service.ScrapingService" <|-- "service.ScrapingServiceImpl"

@enduml
